create table if not exists public.blog_converse_page_links (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.blog_posts(id) on delete cascade,
  url text not null,
  label text not null,
  description text default '',
  icon text default 'sparkles',
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.blog_converse_page_links enable row level security;

create policy "Public can read converse page links"
  on public.blog_converse_page_links for select
  using (true);

create policy "Authenticated admins can insert converse page links"
  on public.blog_converse_page_links for insert
  to authenticated
  with check (true);

create policy "Authenticated admins can update converse page links"
  on public.blog_converse_page_links for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated admins can delete converse page links"
  on public.blog_converse_page_links for delete
  to authenticated
  using (true);
